name: Build Images
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        tags: |
          foo:v1 foo:latest
          bar:v1 bar:latest

        containerfiles: |
          ./images/Containerfile.foo
          ./images/Containerfile.bar
