name: Publish DApp
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello 
        run: |
          tag="${{ github.event.tag_name }}"; widget="${tag#v*-}";
          echo ${widget}
