name: Publish DApp
on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment to deploy DApp
        required: true
        type: choice
        options:
        - dev
        - prod

      data:
        description: DApp compressed data (base64 encoded tar.gz)
        required: true
        type: string

  # push:
  #   branches:
  #     - dennybaa/testing

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo ${toJSON(inputs)}}
