name: Publish DApp
on:
  release:
    types: [released]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello 
        run: |
          tag="${{ github.event.release.tag_name }}"; widget="${tag#v*-}";
          echo ${widget}
