name: Publish DApp
on:
  workflow_dispatch:
    inputs:
      name:
        description: DApp name
        type: string
        required: true

      mode:
        description: Artifacts mode single/multiple
        required: true
        type: choice
        options:
        - single
        - multiple

      dist:
        description: DApp dist Acrhive (base64 encoded compressed tar.gz)
        required: true
        type: string

      ref:
        description: Caller ref
        type: string
        required: true

  # push:
  #   branches:
  #     - dennybaa/testing

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo "Where am I run?"
          echo "--------------------"
          echo "${{ toJSON(github) }}"
          echo
