name: test-pr

on:
  workflow_dispatch:
  pull_request:
    types: [edited]
    branches: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |-
        echo '--------------------'
        echo '${{ toJSON(github.event) }}'
