name: test

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: code

      - name: Checkout Nu modules
        uses: actions/checkout@v4
        with:
          repository: bitdeps/nu_scripts
          path: nu

      - uses: hustcer/setup-nu@main

      - name: prepare-env
        env:
          NU_MODULE_DIRS: nu/modules
          GITHUB_TOKEN: ${{ secrets.MYPAT }}

        shell: nu -c "source nu/scripts/env/common.nu; exec nu -I (nu-include-dirs) {0}"
        run: |-
          ^env
          $nu
