name: test

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: code

      - name: Checkout Nu modules
        uses: actions/checkout@v4
        with:
          repository: bitdeps/nu_scripts
          path: nu_scripts

      - uses: hustcer/setup-nu@main

      - name: prepare-env
        env:
          NU_MODULE_DIRS: nu_scripts/modules
          GITHUB_TOKEN: ${{ secrets.MYPAT }}

        shell: nu {0}
        run: |-
          # load env helpers
          ls ./nu_scripts/modules/common/env.nu
          #; alias nu = nu -I (nu-include-dirs)
          #exec nu code/nu/dispatch.nu
