name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: hustcer/setup-nu@main
      
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: code

      - name: Checkout Nu Modules
        uses: actions/checkout@v4
        with:
          repository: bitdeps/nu_scripts
          path: nu

      - name: Dispatch Workflows
        env:
          GITHUB_TOKEN: ${{ secrets.MYPAT }}
          NU_LOG_LEVEL: info
          NU_MODULE_DIRS: |
            ${{ github.workspace }}/nu/modules
            ${{ github.workspace }}/nu/scripts
        shell: nu {0}
        run: |
          const workspace = '${{ github.workspace }}'
          source $"($workspace)/nu/scripts/common/env.nu"
          
          print ($env | to text)
          print '-------------------------'
          print ($env.NU_MODULE_DIRS)
          print '---'
          print (nu-include-dirs | describe)
          print '+++'
          print $workspace
          #cd code; nu -I (nu-include-dirs) $"($workspace)/nu/scripts/github/dispatch.nu"
