name: test

on:
  push:
    branches:
      - "*"

  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |-
        echo '--------------------'
        echo ${{ inputs.message }}
