name: test-pr

on:
  workflow_dispatch:
    inputs:
      feature:
        description: Feature
        required: false
        type: string

      client:
        description: Client ID
        required: false
        type: string

  pull_request:
    types: [edited]
    branches: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |-
        echo '--------------------'
        echo '${{ toJSON(github.event) }}'
