name: test

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: code

      - name: Checkout Nu modules
        uses: actions/checkout@v4
        with:
          repository: bitdeps/nu_scripts
          path: nu

      - uses: hustcer/setup-nu@main

      - name: prepare-env
        shell: bash -c "echo {0}" 
        env:
          NU_MODULE_DIRS: nu/modules
        run: |
          source ${{ github.workspace }}/nu/scripts/env/setup.nu
          exec nu -I (include-dirs) code/nu/dispatch.nu
